// Code generated by mockgen. DO NOT EDIT.
// Source: internal/domain/action/repository.go

package mocks

import (
	"context"
	"reflect"
	"time"

	"github.com/google/uuid"
	"go.uber.org/mock/gomock"

	"github.com/execution-hub/execution-hub/internal/domain/action"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRepository) Create(ctx context.Context, a *action.Action) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, a)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRepositoryMockRecorder) Create(ctx, a interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepository)(nil).Create), ctx, a)
}

// GetByID mocks base method.
func (m *MockRepository) GetByID(ctx context.Context, actionID uuid.UUID) (*action.Action, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, actionID)
	ret0, _ := ret[0].(*action.Action)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockRepositoryMockRecorder) GetByID(ctx, actionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockRepository)(nil).GetByID), ctx, actionID)
}

// GetByEvaluationID mocks base method.
func (m *MockRepository) GetByEvaluationID(ctx context.Context, evaluationID uuid.UUID) (*action.Action, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEvaluationID", ctx, evaluationID)
	ret0, _ := ret[0].(*action.Action)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEvaluationID indicates an expected call of GetByEvaluationID.
func (mr *MockRepositoryMockRecorder) GetByEvaluationID(ctx, evaluationID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEvaluationID", reflect.TypeOf((*MockRepository)(nil).GetByEvaluationID), ctx, evaluationID)
}

// List mocks base method.
func (m *MockRepository) List(ctx context.Context, filter action.Filter, limit, offset int) ([]*action.Action, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filter, limit, offset)
	ret0, _ := ret[0].([]*action.Action)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockRepositoryMockRecorder) List(ctx, filter, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockRepository)(nil).List), ctx, filter, limit, offset)
}

// Update mocks base method.
func (m *MockRepository) Update(ctx context.Context, a *action.Action) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, a)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockRepositoryMockRecorder) Update(ctx, a interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRepository)(nil).Update), ctx, a)
}

// UpdateStatus mocks base method.
func (m *MockRepository) UpdateStatus(ctx context.Context, actionID uuid.UUID, status action.Status) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, actionID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockRepositoryMockRecorder) UpdateStatus(ctx, actionID, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockRepository)(nil).UpdateStatus), ctx, actionID, status)
}

// FindByDedupeKey mocks base method.
func (m *MockRepository) FindByDedupeKey(ctx context.Context, dedupeKey string, since time.Time) (*action.Action, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByDedupeKey", ctx, dedupeKey, since)
	ret0, _ := ret[0].(*action.Action)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByDedupeKey indicates an expected call of FindByDedupeKey.
func (mr *MockRepositoryMockRecorder) FindByDedupeKey(ctx, dedupeKey, since interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByDedupeKey", reflect.TypeOf((*MockRepository)(nil).FindByDedupeKey), ctx, dedupeKey, since)
}

// RecordTransition mocks base method.
func (m *MockRepository) RecordTransition(ctx context.Context, transition *action.StateTransition) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordTransition", ctx, transition)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordTransition indicates an expected call of RecordTransition.
func (mr *MockRepositoryMockRecorder) RecordTransition(ctx, transition interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordTransition", reflect.TypeOf((*MockRepository)(nil).RecordTransition), ctx, transition)
}

// GetTransitions mocks base method.
func (m *MockRepository) GetTransitions(ctx context.Context, actionID uuid.UUID) ([]*action.StateTransition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransitions", ctx, actionID)
	ret0, _ := ret[0].([]*action.StateTransition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransitions indicates an expected call of GetTransitions.
func (mr *MockRepositoryMockRecorder) GetTransitions(ctx, actionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransitions", reflect.TypeOf((*MockRepository)(nil).GetTransitions), ctx, actionID)
}

// ListRetryableActions mocks base method.
func (m *MockRepository) ListRetryableActions(ctx context.Context, limit int) ([]*action.Action, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRetryableActions", ctx, limit)
	ret0, _ := ret[0].([]*action.Action)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRetryableActions indicates an expected call of ListRetryableActions.
func (mr *MockRepositoryMockRecorder) ListRetryableActions(ctx, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRetryableActions", reflect.TypeOf((*MockRepository)(nil).ListRetryableActions), ctx, limit)
}
