// Code generated by mockgen. DO NOT EDIT.
// Source: internal/domain/rule/repository.go

package mocks

import (
	"context"
	"reflect"
	"time"

	"github.com/google/uuid"
	"go.uber.org/mock/gomock"

	"github.com/execution-hub/execution-hub/internal/domain/rule"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRepository) Create(ctx context.Context, r *rule.Rule) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, r)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRepositoryMockRecorder) Create(ctx, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepository)(nil).Create), ctx, r)
}

// GetByRuleID mocks base method.
func (m *MockRepository) GetByRuleID(ctx context.Context, ruleID uuid.UUID) (*rule.Rule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByRuleID", ctx, ruleID)
	ret0, _ := ret[0].(*rule.Rule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByRuleID indicates an expected call of GetByRuleID.
func (mr *MockRepositoryMockRecorder) GetByRuleID(ctx, ruleID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByRuleID", reflect.TypeOf((*MockRepository)(nil).GetByRuleID), ctx, ruleID)
}

// GetByRuleIDAndVersion mocks base method.
func (m *MockRepository) GetByRuleIDAndVersion(ctx context.Context, ruleID uuid.UUID, version int) (*rule.Rule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByRuleIDAndVersion", ctx, ruleID, version)
	ret0, _ := ret[0].(*rule.Rule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByRuleIDAndVersion indicates an expected call of GetByRuleIDAndVersion.
func (mr *MockRepositoryMockRecorder) GetByRuleIDAndVersion(ctx, ruleID, version interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByRuleIDAndVersion", reflect.TypeOf((*MockRepository)(nil).GetByRuleIDAndVersion), ctx, ruleID, version)
}

// GetByID mocks base method.
func (m *MockRepository) GetByID(ctx context.Context, id int64) (*rule.Rule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*rule.Rule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockRepositoryMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockRepository)(nil).GetByID), ctx, id)
}

// ListActiveRules mocks base method.
func (m *MockRepository) ListActiveRules(ctx context.Context, filter rule.Filter) ([]*rule.Rule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListActiveRules", ctx, filter)
	ret0, _ := ret[0].([]*rule.Rule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListActiveRules indicates an expected call of ListActiveRules.
func (mr *MockRepositoryMockRecorder) ListActiveRules(ctx, filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListActiveRules", reflect.TypeOf((*MockRepository)(nil).ListActiveRules), ctx, filter)
}

// ListVersions mocks base method.
func (m *MockRepository) ListVersions(ctx context.Context, ruleID uuid.UUID) ([]*rule.Rule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListVersions", ctx, ruleID)
	ret0, _ := ret[0].([]*rule.Rule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListVersions indicates an expected call of ListVersions.
func (mr *MockRepositoryMockRecorder) ListVersions(ctx, ruleID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListVersions", reflect.TypeOf((*MockRepository)(nil).ListVersions), ctx, ruleID)
}

// UpdateStatus mocks base method.
func (m *MockRepository) UpdateStatus(ctx context.Context, id int64, status rule.RuleStatus, updatedBy *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, id, status, updatedBy)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockRepositoryMockRecorder) UpdateStatus(ctx, id, status, updatedBy interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockRepository)(nil).UpdateStatus), ctx, id, status, updatedBy)
}

// CreateEvaluation mocks base method.
func (m *MockRepository) CreateEvaluation(ctx context.Context, eval *rule.Evaluation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEvaluation", ctx, eval)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateEvaluation indicates an expected call of CreateEvaluation.
func (mr *MockRepositoryMockRecorder) CreateEvaluation(ctx, eval interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEvaluation", reflect.TypeOf((*MockRepository)(nil).CreateEvaluation), ctx, eval)
}

// GetEvaluationByID mocks base method.
func (m *MockRepository) GetEvaluationByID(ctx context.Context, evaluationID uuid.UUID) (*rule.Evaluation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEvaluationByID", ctx, evaluationID)
	ret0, _ := ret[0].(*rule.Evaluation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEvaluationByID indicates an expected call of GetEvaluationByID.
func (mr *MockRepositoryMockRecorder) GetEvaluationByID(ctx, evaluationID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEvaluationByID", reflect.TypeOf((*MockRepository)(nil).GetEvaluationByID), ctx, evaluationID)
}

// ListEvaluationsByRule mocks base method.
func (m *MockRepository) ListEvaluationsByRule(ctx context.Context, ruleID uuid.UUID, limit int) ([]*rule.Evaluation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEvaluationsByRule", ctx, ruleID, limit)
	ret0, _ := ret[0].([]*rule.Evaluation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEvaluationsByRule indicates an expected call of ListEvaluationsByRule.
func (mr *MockRepositoryMockRecorder) ListEvaluationsByRule(ctx, ruleID, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEvaluationsByRule", reflect.TypeOf((*MockRepository)(nil).ListEvaluationsByRule), ctx, ruleID, limit)
}

// ListMatchedEvaluations mocks base method.
func (m *MockRepository) ListMatchedEvaluations(ctx context.Context, since time.Time, limit int) ([]*rule.Evaluation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMatchedEvaluations", ctx, since, limit)
	ret0, _ := ret[0].([]*rule.Evaluation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMatchedEvaluations indicates an expected call of ListMatchedEvaluations.
func (mr *MockRepositoryMockRecorder) ListMatchedEvaluations(ctx, since, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMatchedEvaluations", reflect.TypeOf((*MockRepository)(nil).ListMatchedEvaluations), ctx, since, limit)
}
