// Code generated by mockgen. DO NOT EDIT.
// Source: internal/domain/notification/repository.go

package mocks

import (
	"context"
	"reflect"

	"github.com/google/uuid"
	"go.uber.org/mock/gomock"

	"github.com/industrial-data-source/internal/domain/notification"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRepository) Create(ctx context.Context, n *notification.Notification) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, n)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRepositoryMockRecorder) Create(ctx, n interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepository)(nil).Create), ctx, n)
}

// GetByID mocks base method.
func (m *MockRepository) GetByID(ctx context.Context, notificationID uuid.UUID) (*notification.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, notificationID)
	ret0, _ := ret[0].(*notification.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockRepositoryMockRecorder) GetByID(ctx, notificationID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockRepository)(nil).GetByID), ctx, notificationID)
}

// GetByActionID mocks base method.
func (m *MockRepository) GetByActionID(ctx context.Context, actionID uuid.UUID) ([]*notification.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByActionID", ctx, actionID)
	ret0, _ := ret[0].([]*notification.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByActionID indicates an expected call of GetByActionID.
func (mr *MockRepositoryMockRecorder) GetByActionID(ctx, actionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByActionID", reflect.TypeOf((*MockRepository)(nil).GetByActionID), ctx, actionID)
}

// List mocks base method.
func (m *MockRepository) List(ctx context.Context, filter notification.Filter, limit, offset int) ([]*notification.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filter, limit, offset)
	ret0, _ := ret[0].([]*notification.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockRepositoryMockRecorder) List(ctx, filter, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockRepository)(nil).List), ctx, filter, limit, offset)
}

// Update mocks base method.
func (m *MockRepository) Update(ctx context.Context, n *notification.Notification) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, n)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockRepositoryMockRecorder) Update(ctx, n interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRepository)(nil).Update), ctx, n)
}

// UpdateStatus mocks base method.
func (m *MockRepository) UpdateStatus(ctx context.Context, notificationID uuid.UUID, status notification.Status) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, notificationID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockRepositoryMockRecorder) UpdateStatus(ctx, notificationID, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockRepository)(nil).UpdateStatus), ctx, notificationID, status)
}

// RecordAttempt mocks base method.
func (m *MockRepository) RecordAttempt(ctx context.Context, attempt *notification.DeliveryAttempt) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordAttempt", ctx, attempt)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordAttempt indicates an expected call of RecordAttempt.
func (mr *MockRepositoryMockRecorder) RecordAttempt(ctx, attempt interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordAttempt", reflect.TypeOf((*MockRepository)(nil).RecordAttempt), ctx, attempt)
}

// GetAttempts mocks base method.
func (m *MockRepository) GetAttempts(ctx context.Context, notificationID uuid.UUID) ([]*notification.DeliveryAttempt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAttempts", ctx, notificationID)
	ret0, _ := ret[0].([]*notification.DeliveryAttempt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAttempts indicates an expected call of GetAttempts.
func (mr *MockRepositoryMockRecorder) GetAttempts(ctx, notificationID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAttempts", reflect.TypeOf((*MockRepository)(nil).GetAttempts), ctx, notificationID)
}

// SaveAttemptToDLQ mocks base method.
func (m *MockRepository) SaveAttemptToDLQ(ctx context.Context, attempt *notification.DeliveryAttempt, originalErr error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveAttemptToDLQ", ctx, attempt, originalErr)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveAttemptToDLQ indicates an expected call of SaveAttemptToDLQ.
func (mr *MockRepositoryMockRecorder) SaveAttemptToDLQ(ctx, attempt, originalErr interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveAttemptToDLQ", reflect.TypeOf((*MockRepository)(nil).SaveAttemptToDLQ), ctx, attempt, originalErr)
}

// ListPendingNotifications mocks base method.
func (m *MockRepository) ListPendingNotifications(ctx context.Context, limit int) ([]*notification.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPendingNotifications", ctx, limit)
	ret0, _ := ret[0].([]*notification.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPendingNotifications indicates an expected call of ListPendingNotifications.
func (mr *MockRepositoryMockRecorder) ListPendingNotifications(ctx, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPendingNotifications", reflect.TypeOf((*MockRepository)(nil).ListPendingNotifications), ctx, limit)
}

// ListRetryableNotifications mocks base method.
func (m *MockRepository) ListRetryableNotifications(ctx context.Context, limit int) ([]*notification.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRetryableNotifications", ctx, limit)
	ret0, _ := ret[0].([]*notification.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRetryableNotifications indicates an expected call of ListRetryableNotifications.
func (mr *MockRepositoryMockRecorder) ListRetryableNotifications(ctx, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRetryableNotifications", reflect.TypeOf((*MockRepository)(nil).ListRetryableNotifications), ctx, limit)
}

// ExpireNotifications mocks base method.
func (m *MockRepository) ExpireNotifications(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExpireNotifications", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExpireNotifications indicates an expected call of ExpireNotifications.
func (mr *MockRepositoryMockRecorder) ExpireNotifications(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExpireNotifications", reflect.TypeOf((*MockRepository)(nil).ExpireNotifications), ctx)
}

// MockSSEHub is a mock of SSEHub interface.
type MockSSEHub struct {
	ctrl     *gomock.Controller
	recorder *MockSSEHubMockRecorder
}

// MockSSEHubMockRecorder is the mock recorder for MockSSEHub.
type MockSSEHubMockRecorder struct {
	mock *MockSSEHub
}

// NewMockSSEHub creates a new mock instance.
func NewMockSSEHub(ctrl *gomock.Controller) *MockSSEHub {
	mock := &MockSSEHub{ctrl: ctrl}
	mock.recorder = &MockSSEHubMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSSEHub) EXPECT() *MockSSEHubMockRecorder {
	return m.recorder
}

// Register mocks base method.
func (m *MockSSEHub) Register(client *notification.SSEClient) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Register", client)
}

// Register indicates an expected call of Register.
func (mr *MockSSEHubMockRecorder) Register(client interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockSSEHub)(nil).Register), client)
}

// Unregister mocks base method.
func (m *MockSSEHub) Unregister(clientID string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Unregister", clientID)
}

// Unregister indicates an expected call of Unregister.
func (mr *MockSSEHubMockRecorder) Unregister(clientID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unregister", reflect.TypeOf((*MockSSEHub)(nil).Unregister), clientID)
}

// GetClient mocks base method.
func (m *MockSSEHub) GetClient(clientID string) *notification.SSEClient {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClient", clientID)
	ret0, _ := ret[0].(*notification.SSEClient)
	return ret0
}

// GetClient indicates an expected call of GetClient.
func (mr *MockSSEHubMockRecorder) GetClient(clientID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClient", reflect.TypeOf((*MockSSEHub)(nil).GetClient), clientID)
}

// GetClientCount mocks base method.
func (m *MockSSEHub) GetClientCount() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClientCount")
	ret0, _ := ret[0].(int)
	return ret0
}

// GetClientCount indicates an expected call of GetClientCount.
func (mr *MockSSEHubMockRecorder) GetClientCount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClientCount", reflect.TypeOf((*MockSSEHub)(nil).GetClientCount))
}

// BroadcastToAll mocks base method.
func (m *MockSSEHub) BroadcastToAll(message *notification.SSEMessage) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "BroadcastToAll", message)
}

// BroadcastToAll indicates an expected call of BroadcastToAll.
func (mr *MockSSEHubMockRecorder) BroadcastToAll(message interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BroadcastToAll", reflect.TypeOf((*MockSSEHub)(nil).BroadcastToAll), message)
}

// BroadcastToUser mocks base method.
func (m *MockSSEHub) BroadcastToUser(userID string, message *notification.SSEMessage) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "BroadcastToUser", userID, message)
}

// BroadcastToUser indicates an expected call of BroadcastToUser.
func (mr *MockSSEHubMockRecorder) BroadcastToUser(userID, message interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BroadcastToUser", reflect.TypeOf((*MockSSEHub)(nil).BroadcastToUser), userID, message)
}

// BroadcastToGroup mocks base method.
func (m *MockSSEHub) BroadcastToGroup(group string, message *notification.SSEMessage) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "BroadcastToGroup", group, message)
}

// BroadcastToGroup indicates an expected call of BroadcastToGroup.
func (mr *MockSSEHubMockRecorder) BroadcastToGroup(group, message interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BroadcastToGroup", reflect.TypeOf((*MockSSEHub)(nil).BroadcastToGroup), group, message)
}

// SendToClient mocks base method.
func (m *MockSSEHub) SendToClient(clientID string, message *notification.SSEMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendToClient", clientID, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendToClient indicates an expected call of SendToClient.
func (mr *MockSSEHubMockRecorder) SendToClient(clientID, message interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendToClient", reflect.TypeOf((*MockSSEHub)(nil).SendToClient), clientID, message)
}

// Start mocks base method.
func (m *MockSSEHub) Start(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Start", ctx)
}

// Start indicates an expected call of Start.
func (mr *MockSSEHubMockRecorder) Start(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockSSEHub)(nil).Start), ctx)
}

// Stop mocks base method.
func (m *MockSSEHub) Stop() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop")
}

// Stop indicates an expected call of Stop.
func (mr *MockSSEHubMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockSSEHub)(nil).Stop))
}
